### ISSUE TITLE
I've added this awesome app to the gallery at awesome-streamlit.org. Hope its OK?

### ISSUE THREAD

**Issue by MarcSkovMadsen** [paduel/streamlit_finance_chart#1]
Hi Paduel

Great App. I've added it to the gallery at [awesome-streamlit.org](https://awesome-streamlit.org). Hope it is Ok?

![image](https://user-images.githubusercontent.com/42288570/67613094-a4ec6400-f7a9-11e9-8a9a-d164850e3429.png)

I can see that we are both in the quant space. So maybe we will touch base again another time. :-)

Thanks

Marc

**Comment by paduel** [comment]
Hi @MarcSkovMadsen.

This sound great for me! Open source  is for sharing and divulgation.

I love your project, and it helped me get to know this great tool that is Streamlit.

Whenever you want, we'll talk about quant and code.

Antonio.
